# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-30 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '在线'), (1, '已下线'), (2, '未知'), (3, '故障'), (4, '备用')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='server',
            name='sub_asset_type',
            field=models.SmallIntegerField(choices=[(0, 'PC服务器'), (1, '刀片机'), (2, '小型机')], default=0, verbose_name='服务器类型'),
        ),
    ]
