# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-31 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20180130_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='os_distribution',
            field=models.CharField(blank=True, default='Ubuntu Server', max_length=64, null=True, verbose_name='发行版本'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_release',
            field=models.CharField(blank=True, default='16.04.3 LTS', max_length=64, null=True, verbose_name='操作系统版本'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_type',
            field=models.CharField(blank=True, default='Linux', max_length=64, null=True, verbose_name='操作系统类型'),
        ),
        migrations.AlterField(
            model_name='server',
            name='raid_type',
            field=models.CharField(blank=True, default='RAID 5', max_length=512, null=True, verbose_name='raid类型'),
        ),
    ]
